//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string ClientID { get; set; }
        public string PayeeID { get; set; }
        public string AccountNumber { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime BillingDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Payee Payee { get; set; }
    }
}
