//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Accounts = new HashSet<Account>();
            this.Payments = new HashSet<Payment>();
        }
    
        public string AccessID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public string Postaladdr { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Login Login { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
